### PR TITLE
A couple of bug-fixes and improvements to documentation

### LINKED ISSUE #12: [BUG] HBN sex values that don't make sense
**Describe the bug**
I think that the function `read.afq.hbn` contains some erroneous data munging, which results in values of the `sex` column that don't make sense.

**To Reproduce**

```
> df_afq <- read.afq.hbn()
> unique(df_afq$sex)
 [1] "F"                 "M"                 "0.005"             "0.936"             "0.987"             "0.017"            
 [7] "0.958"             "0.960034199722988" "0.97"              "0.934"             "0.979"             "0.976224451500692"
```

**Expected behavior**

I would have expected only `"M"` and `"F"`

### PR DESCRIPTION
**Pull request by arokem**
Fixes #12

### CODE REVIEW

**Comment by richford** [comment]
@arokem, Any idea why this is failing now? It seems like the factor subject Ids are breaking this. Perhaps we need to rewrite the tests to account for this.

**Comment by arokem** [comment]
Not sure. I'll take another look later tonight.

**Comment by arokem** [comment]
I don't think that it's because of the subjects-as-factors though, because of this commit and associated commit message: https://github.com/yeatmanlab/tractr/pull/13/commits/cbb152d846811d94f48e8e0667496a914d782003

**Comment by arokem** [comment]
Merging, as discussed with @richford and @mckenziephagen on our call earlier today.

**Pull request merged**
